print("ig:ptnrfif07_")
print("jangan lupa tidur")
print("jangan lari")
print("hati hati dijalan")
print("selamat pagi")
print("secukupnya aja klo kebnyakan nnti kenyang")
print("terlalu banyak insecure sampai lupa bersyukur")
print("jalani,nikmati,syukuri")
print("hidup itu berjalan,kalo cape gojek aja")
print("senyum dikit dong,biar sakitnya ga terlalu keliatan")